import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SessionProvider from './SessionProvider';
import { getSession } from 'next-auth/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='min-h-screen'>
        {/* <SessionProvider session={session}>{children}</SessionProvider> */}
        {children}
      </body>
    </html>
  );
}
